### ISSUE TITLE
covers not show

### ISSUE THREAD

**Issue by keyreel** [jailsonsb2/RadioPlayer#2]
covers not show, I tried both spotify and deezer providers

**Comment by jailsonsb2** [comment]
I would like to know more about your streaming setup. Could you share the URL of your stream, a screenshot of the settings in your get_stream_title.php file, and your index file?

**Comment by jailsonsb2** [comment]
I would like to know more about your streaming setup. Could you share the URL of your stream, a screenshot of the settings in your script.js?

**Comment by keyreel** [comment]
It's ok now.
