### ISSUE TITLE
twj.es

### ISSUE THREAD

**Issue by keyreel** [jailsonsb2/RadioPlayer#3]
From time to time twj.es stops working on the radio_info endpoint.

https://twj.es/radio_info/?radio_url=https://stream.radiorostova.ru/radio-rostova-high.mp3 shows THE GLASS of Foo Fighters - the last playing of the song was yesturday at 23:15. 

At the same time, https://twj.es/get_stream_title/?url=https://stream.radiorostova.ru/radio-rostova-high.mp3 shows correct information.

Is it possible to avoid this stucking?

**Comment by jailsonsb2** [comment]
I'm going to check what's happening

**Comment by keyreel** [comment]
Hi, the same issue again.

**Comment by jailsonsb2** [comment]
https://twj.es/radio_info/?radio_url=https://stream.radiorostova.ru/radio-rostova-high.mp3 . Now the database is being used to persist the data. Much faster and much more reliable with a history of when it was executed.

**Comment by keyreel** [comment]
![2024-07-29_10-42-53](https://github.com/user-attachments/assets/a7411091-9d5a-49c8-a21d-27da1e552a90)
do not work :(

**Comment by keyreel** [comment]
Is it possible to make such a work somehow on the site side, to avoid dependency on the script?
