### ISSUE TITLE
twj.es agaim

### ISSUE THREAD

**Issue by keyreel** [jailsonsb2/RadioPlayer#5]
[twj.es ](https://twj.es/radio_info/?radio_url=https://stream.radiorostova.ru/radio-rostova-high.mp3) sometimes returns correct data, but sometimes - old not actual songs.

**Comment by jailsonsb2** [comment]
I will upload a new version I made soon

**Comment by jailsonsb2** [comment]
https://radioplayer.icu/api2.php?url=

**Comment by keyreel** [comment]
New url don't working for me:
![2024-07-17_10-24-52](https://github.com/user-attachments/assets/975dba08-26d4-4bcf-89bd-cff5756a887f)
