### ISSUE TITLE
new url

### ISSUE THREAD

**Issue by keyreel** [jailsonsb2/RadioPlayer#6]
Hi, sorry, but new URL do not works for me
![2024-07-17_10-24-52](https://github.com/user-attachments/assets/a45ac952-aa06-467c-88e8-ac2ed1c3f20c)

**Comment by jailsonsb2** [comment]
Now the database is being used to persist the data. Much faster and much more reliable with a history of when it was executed.

**Comment by jailsonsb2** [comment]
https://twj.es/
