### ISSUE TITLE
Api.php error

### ISSUE THREAD

**Issue by DAMaia1989** [jailsonsb2/RadioPlayer#8]
Hi Jailson, I think something is wrong in the api.php file. When I try to open a URL I always get the error shown in the attached image. I've already tried it with other links like the one on your demo radio and it doesn't work either.
![api_error](https://github.com/user-attachments/assets/a1e2dff7-c28f-4e14-8455-7e8cdc892e6f)

**Comment by jailsonsb2** [comment]
I updated the API tonight and now it will be much more stable. Visit twj.es
